#!/usr/bin/env bash
set -euo pipefail

: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"

PWABUILDER_ENDPOINT="https://pwabuilder-cloudapk.azurewebsites.net/generateAppPackage"
RELEASE_TAG="v1.0.0"
RELEASE_TITLE="Release 1"

python3 <<'PY'
from pathlib import Path

server = Path("src/server.mjs")
text = server.read_text()

public_anchor = '"/sw.js", "/offline.html"]);'
public_replacement = '"/sw.js", "/offline.html", "/.well-known/assetlinks.json"]);'
if '/.well-known/assetlinks.json' not in text:
    if public_anchor not in text:
        raise SystemExit("Unable to find PUBLIC_FILES anchor in src/server.mjs")
    text = text.replace(public_anchor, public_replacement, 1)

mime_anchor = '    ".js": "text/javascript; charset=utf-8",\n'
json_mime = '    ".json": "application/json; charset=utf-8",\n'
if json_mime not in text:
    if mime_anchor not in text:
        raise SystemExit("Unable to find MIME map anchor in src/server.mjs")
    text = text.replace(mime_anchor, mime_anchor + json_mime, 1)

server.write_text(text)
asset_dir = Path("public/.well-known")
asset_dir.mkdir(parents=True, exist_ok=True)
asset_file = asset_dir / "assetlinks.json"
if not asset_file.exists():
    asset_file.write_text("[]\n")
PY

cat > docs/ANDROID_TWA.md <<'EOF'
# Android Trusted Web Activity

The Android package is generated by the official PWABuilder Android packaging service,
which wraps the hosted web app in a Trusted Web Activity (TWA).

Release 1 uses:

- package ID: `net.dudiebug.chores`
- version: `1.0.0.0` / version code `1`
- runtime origin: `https://chores.dudiebug.net`
- start path: `/login`
- display mode: `standalone`
- notification delegation: enabled

`public/.well-known/assetlinks.json` is generated from the actual Release 1 signing
certificate and is served publicly by the Node service. This Digital Asset Links file
is required for the TWA to open without browser chrome.

The release contains an encrypted recovery copy of the Android signing material. It is
encrypted to `android/release-signing-recovery-public.pem`. The matching recovery key
is intentionally stored separately from GitHub. The same Android signing certificate
must be used for future APKs to install over Release 1.
EOF

corepack enable
COREPACK_ENABLE_DOWNLOAD_PROMPT=0 COREPACK_ENABLE_AUTO_PIN=0 corepack pnpm@11.16.0 install --frozen-lockfile
corepack pnpm@11.16.0 test

rm -rf dist package signing-backup pwabuilder-package.zip release-1-signing-backup.tar.gz
mkdir -p dist package

jq -n \
  --arg host "https://chores.dudiebug.net" \
  --arg manifest "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/public/manifest.webmanifest" \
  --arg icon "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/public/icon-512.png" \
  '{
    additionalTrustedOrigins: [],
    appVersion: "1.0.0.0",
    appVersionCode: 1,
    backgroundColor: "#faf9f6",
    display: "standalone",
    enableNotifications: true,
    enableSiteSettingsShortcut: true,
    fallbackType: "customtabs",
    features: {
      locationDelegation: { enabled: false },
      playBilling: { enabled: false }
    },
    host: $host,
    iconUrl: $icon,
    includeSourceCode: false,
    isChromeOSOnly: false,
    launcherName: "Chores",
    maskableIconUrl: null,
    monochromeIconUrl: null,
    name: "Two of Us Chores",
    navigationColor: "#faf9f6",
    navigationColorDark: "#161e20",
    navigationDividerColor: "#faf9f6",
    navigationDividerColorDark: "#161e20",
    orientation: "portrait-primary",
    packageId: "net.dudiebug.chores",
    serviceAccountJsonFile: null,
    signing: {
      file: null,
      alias: "twoofus",
      fullName: "Dudiebug",
      organization: "Dudiebug",
      organizationalUnit: "Two of Us Chores",
      countryCode: "US",
      keyPassword: "temporary",
      storePassword: "temporary"
    },
    signingMode: "new",
    splashScreenFadeOutDuration: 250,
    startUrl: "/login",
    themeColor: "#faf9f6",
    themeColorDark: "#161e20",
    webManifestUrl: $manifest,
    pwaUrl: $host
  }' > pwabuilder-request.json

echo "Submitting Release 1 to PWABuilder..."
curl --fail-with-body --silent --show-error --location \
  --retry 3 --retry-all-errors --connect-timeout 30 --max-time 1800 \
  -H 'Content-Type: application/json' \
  --data-binary @pwabuilder-request.json \
  "$PWABUILDER_ENDPOINT" \
  -o pwabuilder-package.zip

unzip -t pwabuilder-package.zip
unzip -q pwabuilder-package.zip -d package
find package -maxdepth 4 -type f -print | sort

APK="$(find package -type f -name '*.apk' -print -quit)"
AAB="$(find package -type f -name '*.aab' -print -quit)"
ASSETLINKS="$(find package -type f -name 'assetlinks.json' -print -quit)"
KEYSTORE="$(find package -type f -name '*.keystore' -print -quit)"
KEYINFO="$(find package -type f -iname '*signing*info*.txt' -print -quit)"

test -n "$APK" && test -f "$APK"
test -n "$AAB" && test -f "$AAB"
test -n "$ASSETLINKS" && test -f "$ASSETLINKS"
test -n "$KEYSTORE" && test -f "$KEYSTORE"
test -n "$KEYINFO" && test -f "$KEYINFO"

cp "$APK" dist/two-of-us-chores-release-1.apk
cp "$AAB" dist/two-of-us-chores-release-1.aab
cp "$ASSETLINKS" dist/assetlinks.json
cp "$ASSETLINKS" public/.well-known/assetlinks.json

mkdir -p signing-backup
cp "$KEYSTORE" signing-backup/signing.keystore
cp "$KEYINFO" signing-backup/signing-key-info.txt
tar -C signing-backup -czf release-1-signing-backup.tar.gz signing.keystore signing-key-info.txt
bash android/encrypt-release-signing-backup.sh \
  android/release-signing-recovery-public.pem \
  release-1-signing-backup.tar.gz \
  dist/release-1-signing-recovery-encrypted.tar.gz
rm -rf signing-backup release-1-signing-backup.tar.gz

jq -e '
  (length > 0) and
  ((.[0].relation | index("delegate_permission/common.handle_all_urls")) != null) and
  (.[0].target.namespace == "android_app") and
  (.[0].target.package_name == "net.dudiebug.chores") and
  ((.[0].target.sha256_cert_fingerprints | length) > 0)
' public/.well-known/assetlinks.json >/dev/null

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add src/server.mjs public/.well-known/assetlinks.json docs/ANDROID_TWA.md
if ! git diff --cached --quiet; then
  git commit -m "Add Release 1 Android TWA support"
  git push origin HEAD:main
fi
RELEASE_SHA="$(git rev-parse HEAD)"

if gh release view "$RELEASE_TAG" --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
  echo "Release tag $RELEASE_TAG already exists; refusing to overwrite it." >&2
  exit 1
fi

cat > release-notes.md <<'EOF'
# Release 1

First Android Trusted Web Activity package for **Two of Us Chores**, generated by the
official PWABuilder Android packaging service.

- Android package: `net.dudiebug.chores`
- Version: `1.0.0.0` (version code 1)
- Runtime: `https://chores.dudiebug.net`
- Web Push notification delegation enabled
- Digital Asset Links included for verified TWA operation without browser chrome

Install `two-of-us-chores-release-1.apk` directly on Android. The `.aab` is included for
possible future Play Store use.

`release-1-signing-recovery-encrypted.tar.gz` is the encrypted recovery copy of the
PWABuilder Android signing key. The matching recovery PEM is intentionally kept outside
GitHub. Keep both for future APK updates.
EOF

gh release create "$RELEASE_TAG" \
  --repo "$GITHUB_REPOSITORY" \
  --target "$RELEASE_SHA" \
  --title "$RELEASE_TITLE" \
  --notes-file release-notes.md \
  dist/two-of-us-chores-release-1.apk \
  dist/two-of-us-chores-release-1.aab \
  dist/assetlinks.json \
  dist/release-1-signing-recovery-encrypted.tar.gz
